require('core/options')
require('core/keymaps')

require('plugins/plugins')
require('plugins/telescope')
require('plugins/lsp')
require('plugins/cmp')
require('plugins/lualine')
require('plugins/nvimtree')
require('plugins/tmux')
require('plugins/treesitter')
require('plugins/autopairs')
